[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sharedrive"
version = "1.0.0"
description = "Convenient connectors to make interoperating and collaborating across multiple content management systems easier"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.10.6",
    "pydantic-settings>=2.7.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "python-dotenv>=1.0.1",
    "typer>=0.24.1",
    "boto3>=1.42.55",
    "google-auth-oauthlib>=1.2.1",
    "google-auth>=2.0",
    "rich>=13.0",
    "msal>=1.33.0",
]   

[project.scripts]
sharedrive = "sharedrive.cli:main"

[project.optional-dependencies]

docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.1",
]


[dependency-groups]
dev = [
    "ruff>=0.11.5",
    {include-group = "test"}
]
test = [
    "pytest"
]

[tool.setuptools]
packages = ["sharedrive", "sharedrive.auth", "sharedrive.clients", "sharedrive.commands"]

[tool.ruff]
line-length = 88
indent-width = 4
exclude = ["submodules"]

[tool.ruff.format]
quote-style = "double"
line-ending = "auto"
docstring-code-format = true
skip-magic-trailing-comma = true
preview = true  # Enables improved formatter behavior

[tool.pytest.ini_options]
testpaths = ["tests"]
